version: "3"

services:
  eureka:
    build: ./eurekaserver
    ports:
      - "8761:8761"
  license:
    build: ./license-service
    ports:
      - "8080:8080"
    links:
      - eureka
      - organizatiion

  organizatiion:
    build: ./organization-service
    ports:
      - "8090:8090"
    links:
      - eureka

